### ISSUE TITLE
`basictool` gets stuck trying to convert file

### ISSUE THREAD

**Issue by tom-seddon** [ZornsLemma/basictool#9] opened 2023-04-29 18:51 UTC
When I run `basictool --ascii` on the attached file, I get some gibberish printed and it gets stuck in an infinite loop of some kind.

```
tmbp ~/github/beeb/tests/TextToBBCBASIC % basictool --ascii corpus/a5543a07689b08fced8189da6de5dcfb94636e27971a5e8fe14a77f0968c6df7.original.dat
    REM"

    7OSCLILEN ONOSCLILEN ONOSCLIEXTREM�� ���U�c���b��a��`� �O�
    8LEN	5555253503
    8LEN	5555253503
    8LEN	5555253503
    8LEN	5555253503
    8LEN	5555253503
    8LEN	5555253503
    8LEN	5555253503
```
(it goes on forever)

BBC BASIC 4 has no difficulty listing it, though it looks like there are some embedded control codes in the listing.

[a5543a07689b08fced8189da6de5dcfb94636e27971a5e8fe14a77f0968c6df7.original.dat.zip](https://github.com/ZornsLemma/basictool/files/11359882/a5543a07689b08fced8189da6de5dcfb94636e27971a5e8fe14a77f0968c6df7.original.dat.zip)

**Comment by tom-seddon** [comment] 2023-04-29 18:52
This is on macOS btw. Compiler version:

```
% gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ZornsLemma** [comment] 2023-04-29 19:59
Hi Tom,

Thanks for reporting this. I can reproduce it on Linux x64.

The problem is that basictool is trying to auto-detect whether the input is tokenised BASIC or ASCII BASIC. Because this file has machine code tagged on at the end, the heuristic basictool uses (in driver.c's load_basic() function):
```
        // http://beebwiki.mdfs.net/Program_format says a Wilson/Acorn format   
        // tokenised BASIC program will end with <cr><ff>.                      
        tokenised = ((length >= 2) && (data[length - 2] == '\x0d') &&           
                     (data[length - 1] == '\xff'));                             
```
is deciding the input is ASCII BASIC, and it therefore tries to type it in at the BASIC prompt on the emulated BBC instead of loading the file directly untouched into the emulated machine's RAM.

If you use the --input-tokenised option to explicitly specify the input is tokenised BASIC it should work (and seem to for me).

I don't much like the way it is behaving at the moment, but I am not quite sure what the best thing to do is. I do want basictool to auto-detect the input file format rather than relying on file extensions to tell it how to behave. basictool could try to do some extra sanity checks before deciding something is ASCII, but in general I wonder if there's a risk of it rejecting valid input (the user might be trying to embed control characters in their program, for example).

I'm open to suggestions on how to handle this. I also haven't yet investigated exactly why it locks up, it might be that there is something that could be improved there anyway.

**Comment by ZornsLemma** [comment] 2023-04-29 20:10
Maybe I could tweak the heuristic to be "if the two byte sequence \x0d\xff appears anywhere in the input, it is tokenised BASIC"? While theoretically possible, it's probably not that likely someone will try to tokenise ASCII BASIC which includes that precise double-byte sequence as embedded control characters.

```
$ xxd awkward.bas
00000000: 3130 5052 494e 5420 2249 2061 6d20 6177  10PRINT "I am aw
00000010: 6b77 6172 643a 200d ff22 3b0a 3230 474f  kward: ..";.20GO
00000020: 544f 2031 300a                           TO 10.
$ basictool awkward.bas
```
would no longer work properly, but maybe no one would care, whereas your problem is at least non-contrived.

**Comment by tom-seddon** [comment] 2023-04-29 22:06
Thanks for the reply, and `--input-tokenised` is just the ticket (With this option, `basictool` now also works fine with a few other BASIC files I'd found that were causing it trouble!) I think this can be classed as not a bug, as any autodetection mechanism can always fail.

Regarding alternative means of auto-detection, BeebLink auto-detects BBC BASIC files by starting from the beginning of the file and looking for a non-bad program: https://github.com/tom-seddon/beeblink/blob/d06494852c8b4a58e11e9fc51ee389c6a2279e39/server/utils.ts#L765 - this has no problem with the somewhat common case of BASIC programs with some data stored after `TOP`, as it will naturally find the terminating `0d ff` and it doesn't matter whether it's at the end of the file or not.

To handle infinite loop-type situations, I don't think there's much that can be done except impose a limit on emulated execution time. If `basictool` fails explicitly if the time is exceeded, and there's also a means of increasing it (should this ever be hit in a realistic situation), then you'd at least never get a silent failure from this.

**Comment by tom-seddon** [comment] 2023-04-29 22:10
This gets me wondering what the worst case BBC BASIC program is!

I assume `LIST` has to make a linear search through the keyword table to find the string for each token. So maybe every line needs to be like 240 `d3 HIMEM` tokens, that being the last in the list?

Or would it be worse to have one `d3` token per line, and a lot of lines??

**Comment by ZornsLemma** [comment] 2023-04-29 23:06
Thanks Tom! I really like BeebLink's auto-detection, that's clever and should be really reliable. I've experimentally implemented this in basictool and it seems to work fine. Are you OK for me to include this (rewritten in C) function from your code in my repo? basictool is MIT licensed and I see your code is GPLv3+ so I wanted to check before I commit this. (I'll credit you as the source of the algorithm, of course.)

The worst case is an interesting idea! I haven't tried it, nor do I claim to be any kind of expert on BASIC's internals, but my gut feeling is that you get more tokens in memory by cramming as many as possible on to each line and that's going to increase the execution time more than adding some relatively cheap next line searches (since presumably BASIC just adds on the line length to get to the next line).

Since basictool also runs things like ABE's pack, I think I will try to avoid implementing an execution time limit for now, but it's good to keep the idea around for the future.

**Comment by tom-seddon** [comment] 2023-04-30 00:02
Sure, no problem with reproducing it! And I don't really deserve any credit for it, because I think I just looked at what Matt G's BBCBasicToText.py did to extract all the lines from a BASIC program, and copied that...

(What I'm doing at the moment, which was how I found this case, is updating BBCBasicToText.py to ensure that its output matches that of the BASIC ROM on all the BASIC files I've got.)

**Comment by ZornsLemma** [comment] 2023-04-30 00:08
Thanks Tom. I still think it's a nifty idea to do this "walking" process as a validity check, even when you're not actually trying to decode the BASIC. I'll push out a new release and post on stardot to invite testers before I tag it up as 0.10.

I kind of look forward to any future reports on additional issues, in the unlikely event there are any more bugs in basictool. :-)

**Comment by ZornsLemma** [comment] 2023-04-30 18:22
I'll close this now I've committed a fix to master for it.

**Closed by ZornsLemma** 2023-04-30 18:22 UTC
